services:
  - type: web
    name: smart-home-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: PORT
        value: 10000
